class CreateMembers < ActiveRecord::Migration
  def change
    create_table :members do |t|
      t.boolean :terms_agree
      t.integer :membership_no
      t.integer :receipt_no
      t.date :membership_register_date
      t.string :membership_class
      t.date :date_of_admission
      t.string :branch
      t.string :type_human
      t.string :first_name
      t.string :middle_name
      t.string :last_name
      t.date :date_of_birth
      t.string :gender
      t.string :occupation
      t.string :address_1
      t.string :address_2
      t.string :village
      t.string :taluka
      t.string :city
      t.integer :pin
      t.string :state
      t.string :email
      t.string :contact_no
      t.string :mobile_no
      t.string :mobile_2
      t.string :have_you_disability
      t.string :type_disability
      t.integer :percentage_disability
      t.integer :since_age
      t.string :disability_reason
      t.string :marital_status
      t.date :wedding_anniversary_date
      t.string :spouse_type
      t.string :spouse_firstt_name
      t.string :spouse_middle_name
      t.string :spouse_sur_name
      t.integer :no_of_family_members
      t.integer :kids
      t.string :parents_dependent_on_you
      t.string :standard_passed
      t.string :professional_Qualification
      t.string :es_address_1
      t.string :es_address_2
      t.string :es_city
      t.integer :es_pin
      t.string :es_state
      t.string :es_tell
      t.string :es_email
      t.string :designation
      t.string :department
      t.string :occupation_details
      t.string :annual_income
      t.string :unemployed_registered_details
      t.integer :unemployed_registration_no
      t.date :employment_registration_date
      t.string :do_you_have_blindness
      t.string :blindness_issued_dr_name
      t.string :place
      t.string :certificate_no
      t.date :certificate_date
      t.integer :percent_blindness_stated
      t.string :do_you_know_braille
      t.boolean :member_braille_books_circulating_library
      t.boolean :self_employment_aid
      t.boolean :scholarship_student_aid_scheme
      t.boolean :member_of_braille_jagriti_magazine
      t.boolean :placement_services
      t.boolean :medical_aid
      t.boolean :fgnp
      t.boolean :counselling_services
      t.boolean :any_others
      t.boolean :form_details
      t.string :introduces_by
      t.date :member_submited_form_date
      t.boolean :old_member
      t.string :f_place
      t.boolean :clerk_flag
      t.boolean :admin_flag
      t.string :id_proup
      t.string :id_no
      t.timestamps null: false
    end
  end
end
